---
- hosts: centos
  become: yes
  gather_facts: no
  tasks:
    - name : Install Web Server
      yum: {name: httpd, state: installed}
    - name: Start WEb Servert
      service: {name: httpd, state: started}
...
