---
- hosts: all
  gather_facts: yes
  become: yes
  tasks: 
    - name: Install WebServer on CentOS
      yum: 
        name: httpd
        state: installed
      when: ansible_distribution == "CentOS"

    - name: Install WebServer on Ubuntu
      apt:
        name: apache2
        state: installed
      when: ansible_distribution == "Ubuntu"
